apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0edb7177d2c8e304c

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeName: efs-pv
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata: 
  name: efs-pod
  labels:
    purpose: efs-static
spec:
  volumes:
  - name: efs-static-volume
    persistentVolumeClaim: 
      claimName: efs-claim
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: efs-static-volume
      mountPath: /usr/share/nginx/html

---
apiVersion: v1
kind: Service
metadata: 
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30072